---
# tasks file for ansible-cloud-sql-proxy

# Install cloud-sql-proxy on Linux system.
- block:
  - name: Create cloud-sql-proxy directory
    file: path=/opt/cloudsqlproxy/ state=directory mode="a+rw"

  - name: Get cloud-sql-proxy.
    get_url:
      url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
      dest: "/opt/cloudsqlproxy/cloud-sql-proxy"
      mode: 0755
    when: ansible_architecture == 'x86_64'

  - name: Get cloud-sql-proxy.
    get_url:
      url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.arm64
      dest: "/opt/cloudsqlproxy/cloud-sql-proxy"
      mode: 0755
    when: ansible_architecture == 'arm64'

  - name: Verify cloud-sql-proxy exists
    stat: path=/opt/cloudsqlproxy/cloud-sql-proxy
    register: cloud_sql_proxy_stat

  - name: Configure cloud-sql-proxy on system bin.
    file:
      src: "/opt/cloudsqlproxy/cloud-sql-proxy"
      dest: "/usr/bin/cloud-sql-proxy"
      state: link
    when: cloud_sql_proxy_stat.stat.exists

  - name: Configure cloud-sql-proxy on system sbin.
    file:
      src: "/opt/cloudsqlproxy/cloud-sql-proxy"
      dest: "/usr/sbin/cloud-sql-proxy"
      state: link
    when: cloud_sql_proxy_stat.stat.exists
  when: ansible_system == "Linux"

#Install cloud-sql-proxy on MacOS system.
- name: Create cloud-sql-proxy
  homebrew:
    name: cloud-sql-proxy
    state: present
  when: ansible_os_family == 'Darwin'

# Is cloud-sql-proxy installed?
- command: cloud-sql-proxy --version
  register: result
  failed_when: false
  changed_when: false

- debug:
    var: result.stdout